/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lecture5gradle;

import org.junit.Test;
import static org.junit.Assert.*;

public class AddTest {
    @Test public void testCalculatorAdd() {
        Calculator calculator = new Calculator();
        int result = calculator.add(1, 2);

        assertEquals(3, result);
    }
}
