/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lecture5gradle;

import org.junit.Test;
import static org.junit.Assert.*;

public class SubTest {
    @Test public void testCalculatorSub() {
        Calculator calculator = new Calculator();
        int result = calculator.sub(1, 2);

        assertEquals(-1, result);
    }
}
